name: Deployment

on:
  release:
    types: [published]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@swan-lake-release
              with:
                  args:
                      build -a -c
              env:
                  stripeToken: ${{ secrets.stripeToken }}
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@swan-lake-release
              with:
                  args:
                      push -a
              env:
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
